### ISSUE TITLE
urdf not linking to parent

### ISSUE THREAD

**Issue by JanTromp** [crigroup/robotiq#5]
Hey,
When i run the display.launch everything works fine, but when i connect the "robotiq_85_base_link" to my parent link (fts_robotside) the following happens:
Base_link - gets properly attached
All the fingers, nuckels and fingertips are not connected to the base_link. 

I tried making a new urdf where i connect base_link to a world_link, which works, but when i connect it to my robot (fts_robotside) all links fail except for the base_link.

Any idea what causes this?

Kind regards,
Jan Tromp

**Comment by JanTromp** [comment]
Update:
I don't know what caused the problem exactly but it had something to do with the joints of the fingers to the base.
I made a new URDF where i made those joints fixed. This solved the problem.
The gripper is now in always open position, but that doesn't really matter since i control the gripper via the robotiq node.

**Comment by felixvd** [comment]
Could you post the URDF and which parts you changed?

**Comment by JanTromp** [comment]
Sure:

[custom_gripper_macro.txt](https://github.com/crigroup/robotiq/files/3155987/custom_gripper_macro.txt)

Basically this is changed:

>  <joint name="left_outer_knucle_2_base_joint" type="fixed">     
>       <origin xyz="0 -0.0306011 0.054904" rpy="0 0 ${pi}"/>
>       <parent link="robotiq_base_link" />
>       <child link="left_outer_knuckle_link" />
>     </joint>
> 
>     <joint name="left_inner_knuckle_2_base_joint" type="fixed">
>       <origin xyz="0 0.0127 0.06142" rpy="0 0 0"/>
>       <parent link="robotiq_base_link" />
>       <child link="left_inner_knuckle_link" />
>     </joint>
> 
>     <joint name="left_outer_finger_2_outer_knuckle_joint" type="fixed">
>       <origin xyz="0 0.0315 -0.0041" rpy="0 0 0"/>
>       <parent link="left_outer_knuckle_link" />
>       <child link="left_outer_finger_link" />
>       <axis xyz="1 0 0" />
>     </joint>
> 
>     <joint name="left_inner_finger_2_outer_finger" type="fixed">
>       <origin xyz="0 0.0061 0.0471" rpy="0 0 0"/>
>       <parent link="left_outer_finger_link" />
>       <child link="left_inner_finger_link" />
>     </joint>
> 
>     <joint name="left_inner_finger_pad_2_inner_finger" type="fixed">
>         <origin xyz="0 -0.0220203446692936 0.03242" rpy="0 0 0"/>
>         <parent link="left_inner_finger_link" />
>         <child link="left_inner_finger_pad_link" />
>       </joint>

Plus the same for the other finger.

**Comment by felixvd** [comment]
If the original is `robotiq_85_gripper.urdf.xacro` it looks like quite of a lot of changes:

![grippermacro](https://user-images.githubusercontent.com/4535737/57358966-8372ce00-71b1-11e9-8ea5-3a3c90497090.png)

The way that your macro is written is quite strange - without a prefix you cannot have more than one gripper in the scene, because their names will be the same. It makes me suspect that you might have not used the original file properly in your URDF. How did you call it? There is no code in your OP to check, but I would suggest reviewing xacro macros and check what went wrong. The way that the original file is designed is very common, and I have had no issues using it. You might learn something that will be helpful when you use other ROS packages.
